name: Build - Linux

on: [push,pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  # Creating and configuring conda environment on ubuntu based on .yml file
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
  # Installing and running lint based on lint.py runnable file
    - name: Lint with pylint
      run: |
        $CONDA/bin/conda install pylint
        $CONDA/bin/python lint.py --path ./test --threshold 8
        $CONDA/bin/python lint.py --path ./src --threshold 6
  # Installing and running pytest
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest